import smtplib
from email.message import EmailMessage

from app.services.config_service import APP_EMAIL, GOOGLE_APP_PASSWORD, logger
from app.services.extra_check_service import parse_blood_glucose


def send_email(receiver: str, client_name: str, content: str) -> None:
    msg = EmailMessage()
    msg["From"] = APP_EMAIL
    msg["To"] = receiver
    msg["Subject"] = f"STROKE ALERT: {client_name} needs immediate attention"
    msg.set_content(content)
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(str(APP_EMAIL), str(GOOGLE_APP_PASSWORD))
        smtp.send_message(msg)
    logger.info(f"[Contact] Alert email sent to {receiver}")


def send_otp_email(receiver: str, code: str) -> None:
    msg = EmailMessage()
    msg["From"] = APP_EMAIL
    msg["To"] = receiver
    msg["Subject"] = "Sentinel — Your verification code"
    msg.set_content(
        f"Your Sentinel verification code is: {code}\n\nThis code expires in 10 minutes.\n"
        f"If you did not request this, ignore this email."
    )
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(str(APP_EMAIL), str(GOOGLE_APP_PASSWORD))
        smtp.send_message(msg)
    logger.info(f"[Contact] OTP email sent to {receiver}")


def create_report(
    receiver: str,
    stroke_confidence: float,
    client_name: str,
    is_stroke: bool,
    glucose: float | None = None,
) -> str:
    glucose_section = ""
    emergency_services = False
    contact_family = False

    if glucose is not None:
        glucose_result = parse_blood_glucose(glucose)
        glucose_section = f"""
BLOOD GLUCOSE CONTEXT
---------------------
Glucose Level  : {glucose} mg/dL
Assessment     : {glucose_result["message"]}
"""
        emergency_services = glucose_result["emergency_services"]
        contact_family = glucose_result["contact_family"]

    actions = []
    if is_stroke:
        actions.append("  - Call 911 / Emergency Services immediately")
    if emergency_services:
        actions.append("  - CRITICAL: Emergency glucose intervention required")
    if contact_family:
        actions.append("  - Notify family members or emergency contacts")
    if not actions:
        actions.append("  - Monitor patient and reassess")

    report = f"""SENTINEL STROKE DETECTION — ALERT REPORT
==========================================
Patient        : {client_name}
Stroke Detected: {"YES" if is_stroke else "NO"}
Confidence     : {stroke_confidence:.1f} / 100
{glucose_section}
RECOMMENDED ACTIONS
-------------------
{chr(10).join(actions)}

==========================================
This report was auto-generated by the Sentinel stroke detection system.
Do not reply to this email.
"""
    send_email(receiver, client_name, report)
    return report
